export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const DELETE_POSTS_REQUEST = "DELETE_POSTS_REQUEST";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";
export const DELETE_POSTS_FAILURE = "DELETE_POSTS_FAILURE";

export const EDIT_POSTS_REQUEST = "EDIT_POSTS_REQUEST";
export const EDIT_POSTS_SUCCESS = "EDIT_POSTS_SUCCESS";
export const EDIT_POSTS_FAILURE = "EDIT_POSTS_FAILURE";

export const ADD_POSTS_REQUEST = "ADD_POSTS_REQUEST";
export const ADD_POSTS_SUCCESS = "ADD_POSTS_SUCCESS";
export const ADD_POSTS_FAILURE = "ADD_POSTS_FAILURE";

export const SEARCH_POSTS = "SEARCH_POSTS";
